# Generated by Django 4.0.5 on 2022-06-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_permanent_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
