# Generated by Django 4.0.5 on 2022-07-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_post_likes_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
