version: '3.9'

services:
  web:
    build: .
    command: sh ./entrypoint.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ${POSTGRES_DB_VOLUME}
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_USER}
volumes:
  postgres_data:
